spring:
  data:
    mongodb:
      username: root
      password: example
      database: coparts
      port: 27017
      host: localhost
      authentication-database: admin
  datasource:
    url: jdbc:mysql://localhost:3306/coparts
    username: user
    password: root
technomir-api:
  url-to-api: https://api.tehnomir.com.ua
  api-token: cmFkLGcROJnATF0YCpB6sh4kv04s3Z7s
