spring:
  data:
    mongodb:
      username: root
      password: example
      database: vedmik
      port: 27017
      host: localhost
      authentication-database: admin
tehnomir-api:
  url-to-api: https://api.tehnomir.com.uaa
  api-token: cmFkLGcROJnATF0YCpB6sh4kv04s3Z7s