spring:
  data:
    mongodb:
      username: root
      password: example
      database: vedmik
      port: 27017
      host: localhost
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG