version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: coparts
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "coparts"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
    ports: [ "3306:3306" ]
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mongodb-data: {}
  mysql-data: {}

networks:
  default:
    name: coparts_network